version: "3.9"

services:
  auto-forecast:
    build: .
    container_name: auto-forecast-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
